version: "3.3"
services:
  weather:
    container_name: weather
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: php_nginx
    working_dir: /var/www/html
    ports:
      - "8080:80"
    restart: "always"
    volumes:
      - ./docker/http.d:/etc/nginx/http.d
      - ./docker/php-fpm:/usr/local/etc/php-fpm.d/
      - ./:/var/www/html
    networks:
      - weather
networks:
  weather:
    driver: bridge